site_name: MecaMate Signalisation Documentation
site_description: Python library for robot signaling LED, sound (audio, microphone), emergency stop
site_url: https://iudhael.github.io/mecamatesignal/

repo_url: https://github.com/iudhael/mecamatesignal
repo_name: iudhael/mecamatesignal
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - abbr
  - def_list

# Plugins
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src, .]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            heading_level: 2
            members_order: source
            show_signature_annotations: true
            separate_signature: true

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: getting-started.md
  - User Guide:
    - Basic Usage: user-guide/basic-usage.md
    - Command Line Interface: user-guide/cli.md
  - API Reference: api-reference/
  - Troubleshooting: troubleshooting.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iudhael/mecamatesignal
  version:
    provider: mike

# Custom CSS
extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 MecaMate Contributors